#!/usr/bin/env bash
# this Bash script configures an Ubuntu server with the below requirements.

# Requirements:
#    localhost resolves to 127.0.0.2.
#    facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
echo "127.0.0.1	  localhost" ~/hosts.new
echo "8.8.8.8     facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
